"""add mindmap_data and drop lecture_events table

Revision ID: 0d4ef7803de4
Revises: a89e7929926c
Create Date: 2026-06-14 21:16:08.460528
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0d4ef7803de4'
down_revision = 'a89e7929926c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_events')
    op.add_column('lectures', sa.Column('mindmap_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('lectures', 'mindmap_markdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('mindmap_markdown', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('lectures', 'mindmap_data')
    op.create_table('lecture_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lecture_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('offset_seconds', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], name=op.f('lecture_events_lecture_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lecture_events_pkey'))
    )
    # ### end Alembic commands ###
