"""enlarge lectures status column for PROCESSING

Revision ID: a49eb2fdd835
Revises: 0d4ef7803de4
Create Date: 2026-06-14 23:05:04.236922
"""

from alembic import op
import sqlalchemy as sa


revision = 'a49eb2fdd835'
down_revision = '0d4ef7803de4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lectures', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ACTIVE', 'PAUSED', 'PROCESSING', 'COMPLETED', 'FAILED', name='lecturestatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lectures', 'status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'PROCESSING', 'COMPLETED', 'FAILED', name='lecturestatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
