"""add category, duration and offset fields to lectures

Revision ID: a89e7929926c
Revises: c86a6177613c
Create Date: 2026-06-11 23:40:39.643735
"""

from alembic import op
import sqlalchemy as sa


revision = 'a89e7929926c'
down_revision = 'c86a6177613c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_events', sa.Column('offset_seconds', sa.Float(), nullable=False, server_default='0'))
    op.add_column('lecture_segments', sa.Column('offset_seconds', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('lecture_segments', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('lectures', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.add_column('lectures', sa.Column('duration_seconds', sa.Float(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'lectures', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lectures', type_='foreignkey')
    op.drop_column('lectures', 'duration_seconds')
    op.drop_column('lectures', 'category_id')
    op.alter_column('lecture_segments', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('lecture_segments', 'offset_seconds')
    op.drop_column('lecture_events', 'offset_seconds')
    # ### end Alembic commands ###
