"""unify lecture topics and alerts into lecture_events

Revision ID: c86a6177613c
Revises: b8f4b2a1c7d9
Create Date: 2026-06-11 22:54:55.193451
"""

from alembic import op
import sqlalchemy as sa


revision = 'c86a6177613c'
down_revision = 'b8f4b2a1c7d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED', name='lecturestatus', native_enum=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('mindmap_markdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecture_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TOPIC', 'ALERT', name='lectureeventtype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'CRITICAL', name='lectureeventseverity', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecture_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('OBJECTIVE_SINGLE', 'OBJECTIVE_MULTI', 'SUBJECTIVE', name='questiontype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'type',
               existing_type=sa.Enum('OBJECTIVE_SINGLE', 'OBJECTIVE_MULTI', 'SUBJECTIVE', name='questiontype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_table('lecture_segments')
    op.drop_table('lecture_events')
    op.drop_table('lectures')
    # ### end Alembic commands ###
